name: Cache workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules and assets
        uses: actions/cache@v2
        with:
          # Clé unique pour référencer le cache
          # Vous pouvez la modifier à votre convenance
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          # Liste des fichiers/dossiers à mettre en cache
          path: |
            assets/*
            node_modules/*

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: gh-pages
          folder: .
